modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/qyl27/Inkraft/issues"
license = "MIT"

[[mods]]
modId = "inkraft"
version = "${version}"
displayName = "Inkraft"
authors = "qyl27"
description = '''
Use ink language to write your story in Minecraft.
'''
#logoFile = ""

[[dependencies.inkraft]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inkraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inkraft]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"
