architectury {
    platformSetupLoomIde()
    fabric()
}

fabricApi {
    configureTests {
        createSourceSet = true
        modId = "${rootProject.mod_id}-gametest"
        enableClientGameTests = false
    }
}

sourceSets.named('gametest') {
    java.srcDir rootProject.file('src/gametest/java')
    resources.srcDir rootProject.file('src/test/resources')
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    api "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    runtimeOnly "com.terraformersmc:modmenu:${rootProject.fabric_mod_menu_version}"

    implementation(include("net.kyori:adventure-platform-fabric:${rootProject.adventure_platform_version}"))

    common(project(':')) { transitive false }
    shadowBundle project(path: ':', configuration: 'transformProductionFabric')
}
