plugins {
    id 'me.shedaniel.unified-publishing'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

fabricApi {
    configureTests {
        createSourceSet = true
        modId = "${rootProject.mod_id}-gametest"
        enableClientGameTests = false
    }
}

sourceSets.named('gametest') {
    java.srcDir rootProject.file('src/gametest/java')
    resources.srcDir rootProject.file('src/test/resources')
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    api "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    runtimeOnly "com.terraformersmc:modmenu:${rootProject.fabric_mod_menu_version}"

    implementation(include("net.kyori:adventure-platform-fabric:${rootProject.adventure_platform_version}"))

    common(project(':')) { transitive false }
    shadowBundle project(path: ':', configuration: 'transformProductionFabric')
}

unifiedPublishing {
    project {
        displayName = "Inkraft Fabric ${rootProject.mod_version} (MC ${rootProject.minecraft_version})"
        version = "${rootProject.version}-fabric"
        gameVersions = rootProject.game_versions.split(',').toList()
        gameLoaders = ['fabric']
        releaseType = 'release'

        mainPublication tasks.shadowJar

        relations {
            depends {
                curseforge = 'fabric-api'
                modrinth = 'fabric-api'
            }

            optional {
                curseforge = 'modmenu'
                modrinth = 'modmenu'
            }

            includes {
                modrinth = 'adventure-platform-mod'
            }
        }

        curseforge {
            token = Objects.requireNonNullElse(System.getenv('MOD_CURSEFORGE_TOKEN'), "")
            id = rootProject.curseforge_project_id
        }

        modrinth {
            token = Objects.requireNonNullElse(System.getenv('MOD_MODRINTH_TOKEN'), "")
            id = rootProject.modrinth_project_id
        }
    }
}
