import java.time.ZonedDateTime

plugins {
    id 'java'
    id 'maven-publish'
    id 'architectury-plugin' version "${architectury_plugin_version}"
    id 'dev.architectury.loom-no-remap' version "${architectury_loom_version}"
    id 'com.gradleup.shadow' version "${shadow_plugin_version}" apply false
    id 'me.shedaniel.unified-publishing' version "${unified_publishing_version}" apply false
}

def ENV = System.getenv()

base {
    archivesName = "$rootProject.archive_base_name-common"
}

architectury {
    common(project.enabled_platforms.split(','))
}

loom {
    accessWidenerPath = file('src/main/resources/inkraft.accesswidener')

    runConfigs.configureEach {
        ideConfigGenerated = false
    }
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    implementation "com.bladecoder.ink:blade-ink:${rootProject.blade_ink_version}"

    compileOnly "net.kyori:adventure-platform-mod-shared:${rootProject.adventure_platform_version}"
    implementation "net.kyori:adventure-text-serializer-legacy:${rootProject.adventure_version}"

    testImplementation platform("org.junit:junit-bom:${rootProject.junit_version}")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

sourceSets {
    main {
        resources {
            srcDir file('src/generated/resources')
            if (providers.gradleProperty('MOD_DEVELOPMENT').present) {
                srcDir file('src/test/resources')
            }
        }
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = project.base.archivesName.get()
            from components.java
        }
    }
}

allprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'
    apply plugin: 'architectury-plugin'
    apply plugin: 'dev.architectury.loom-no-remap'

    group = rootProject.maven_group
    version = "${rootProject.mod_version}+mc${project.minecraft_version}"

    architectury {
        minecraft = project.minecraft_version
    }

    loom {
        silentMojangMappingsLicense()

        interfaceInjection {
            enableDependencyInterfaceInjection = true
        }
    }

    repositories {
        maven {
            name = 'Mod Menu'
            url = 'https://maven.terraformersmc.com/releases'
        }

        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases/'
        }

        maven {
            name = 'sonatype-oss-snapshots1'
            url = 'https://s01.oss.sonatype.org/content/repositories/snapshots/'
            mavenContent { snapshotsOnly() }
        }

        mavenCentral()
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        implementation "com.bladecoder.ink:blade-ink:${rootProject.blade_ink_version}"

        compileOnly "org.jetbrains:annotations:${rootProject.jetbrains_annotation_version}"
        compileOnly "org.projectlombok:lombok:${rootProject.lombok_version}"
        annotationProcessor "org.projectlombok:lombok:${rootProject.lombok_version}"

        testCompileOnly "org.projectlombok:lombok:${rootProject.lombok_version}"
        testAnnotationProcessor "org.projectlombok:lombok:${rootProject.lombok_version}"
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 25
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }

    java {
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }

    jar {
        from('LICENSE') {
            rename { "${it}_${project.archive_base_name}" }
        }
    }

    var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
        var replaceTokens = [
                build_time                               : ZonedDateTime.now().toString(),
                mod_id                                   : project.mod_id,
                mod_version                              : project.mod_version,
                mod_name                                 : project.mod_name,
                mod_description                          : project.mod_description,
                mod_authors                              : project.mod_authors,
                mod_license                              : project.mod_license,
                mod_sources                              : project.mod_sources,
                mod_issues_page                          : project.mod_issues_page,
                maven_group                              : project.maven_group,
                archive_base_name                        : project.archive_base_name,
                minecraft_version                        : project.minecraft_version,
                neoforge_loader_version                  : project.neoforge_loader_version,
                neoforge_version                         : project.neoforge_version,
                neoforge_minecraft_version_range         : project.neoforge_minecraft_version_range,
                neoforge_loader_version_range            : project.neoforge_loader_version_range,
                neoforge_version_range                   : project.neoforge_version_range,
                neoforge_adventure_platform_version_range: project.neoforge_adventure_platform_version_range,
                fabric_loader_version                    : project.fabric_loader_version,
                fabric_api_version                       : project.fabric_api_version,
                fabric_minecraft_version_range           : project.fabric_minecraft_version_range,
                fabric_loader_version_range              : project.fabric_loader_version_range,
                fabric_api_version_range                 : project.fabric_api_version_range,
                fabric_adventure_platform_version_range  : project.fabric_adventure_platform_version_range,
        ]

        inputs.properties replaceTokens
        expand replaceTokens
        from 'src/main/templates'
        into 'build/generated/sources/mod-metadata'
    }
    sourceSets.main.resources.srcDir generateModMetadata

    processResources {
        dependsOn generateModMetadata
        exclude('.cache/**/*')
    }

    publishing {
        repositories {
            mavenLocal()

            maven {
                name = 'YuluoMaven'

                def releaseUrl = 'https://maven.yuluo.dev/repository/maven-releases/'
                def snapshotUrl = 'https://maven.yuluo.dev/repository/maven-snapshots/'
                url = ENV.MOD_RELEASE ? releaseUrl : snapshotUrl

                credentials {
                    username ENV.MOD_MAVEN_USER
                    password ENV.MOD_MAVEN_PASS
                }
            }
        }
    }
}

subprojects {
    apply plugin: 'com.gradleup.shadow'

    base {
        archivesName = "$rootProject.archive_base_name-${loom.getPlatform().get().id()}"
    }

    loom {
        accessWidenerPath = project(':').loom.accessWidenerPath

        nestJars tasks.named('shadowJar'), project.configurations.include

        runs {
            client {
                client()
                runDirectory = file('run/client')
            }

            server {
                server()
                runDirectory = file('run/server')
            }

            configureEach {
                systemProperties.put('file.encoding', 'UTF-8')
                systemProperties.put('stdout.encoding', 'UTF-8')
                systemProperties.put('stderr.encoding', 'UTF-8')
                systemProperties.put('stdio.encoding', 'UTF-8')

                // To support the Enhanced Class Redefinition in JBR.
                jvmArguments.addAll(
                        '-XX:+IgnoreUnrecognizedVMOptions',
                        '-XX:+AllowEnhancedClassRedefinition',
                )
            }
        }
    }

    configurations {
        common {
            canBeResolved = true
            canBeConsumed = false
        }

        compileClasspath.extendsFrom common
        runtimeClasspath.extendsFrom common
        developmentFabric.extendsFrom common
        developmentNeoForge.extendsFrom common

        shadowBundle {
            canBeResolved = true
            canBeConsumed = false
        }
    }

    dependencies {
        include "com.bladecoder.ink:blade-ink:${rootProject.blade_ink_version}"
        implementation(include("net.kyori:adventure-text-serializer-legacy:${rootProject.adventure_version}"))
    }

    jar {
        archiveClassifier = 'dev'
    }

    shadowJar {
        exclude 'architectury.common.json'
        configurations = [project.configurations.shadowBundle]
        archiveClassifier = ''
    }

    sourcesJar {
        def commonSources = rootProject.sourcesJar
        dependsOn commonSources
        from commonSources.archiveFile.map { zipTree(it) }
    }

    shadow {
        addShadowVariantIntoJavaComponent = false
    }

    publishing {
        publications {
            maven(MavenPublication) {
                artifactId = project.base.archivesName.get()
                from components.java
            }
        }
    }
}
