org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

# Gradle plugins
architectury_plugin_version=3.5-SNAPSHOT
architectury_loom_version=1.17-SNAPSHOT
shadow_plugin_version=9.3.+
mod_publish_plugin_version=2.2.0

# Mod properties
mod_id=inkraft
mod_version=2.0.0
mod_name=Inkraft
mod_description=Use ink language to write your story in Minecraft.
mod_authors=qyl27
mod_license=PolyForm Shield 1.0.0
mod_sources=https://github.com/qyl27/Inkraft
mod_issues_page=https://github.com/qyl27/Inkraft/issues
maven_group=dev.yuluo.mc
archive_base_name=inkraft
enabled_platforms=fabric,neoforge

# Minecraft
minecraft_version=26.1.2

# Loaders
fabric_loader_version=0.19.3
fabric_api_version=0.151.0+26.1.2
neoforge_loader_version=1
neoforge_version=26.1.2.76

# Dependencies
lombok_version=1.18.46
jetbrains_annotation_version=26.1.0
junit_version=5.13.4
blade_ink_version=1.3.2
adventure_platform_version=6.9.0
adventure_version=4.26.1

fabric_mod_menu_version=18.0.0-beta.1

# Version range used in mod metadata
neoforge_minecraft_version_range=[26.1,26.2)
neoforge_loader_version_range=[1,)
neoforge_version_range=[26.1,26.2)
neoforge_adventure_platform_version_range=[6.9,)

fabric_minecraft_version_range=~26.1
fabric_loader_version_range=>=0.18
fabric_api_version_range=*
fabric_adventure_platform_version_range=~6.9

# Publishing
game_versions=26.1,26.1.1,26.1.2
curseforge_project_id=1542671
modrinth_project_id=RUW8h0ml
