architectury {
    platformSetupLoomIde()
    neoForge()
}

sourceSets {
    gametest {
        java.srcDir rootProject.file('src/gametest/java')
        compileClasspath += sourceSets.main.output + sourceSets.main.compileClasspath
        runtimeClasspath += sourceSets.main.runtimeClasspath
        resources.srcDir rootProject.file('src/test/resources')
    }
}

loom {
    runs {
        gameTestServer {
            server()
            forgeTemplate = 'gameTestServer'
            sourceSet = sourceSets.gametest.name
            setRunDirectory file('run/gametestserver')

            mods {
                main {
                    sourceSet sourceSets.main
                    sourceSet sourceSets.gametest
                }
            }
        }

        data {
            clientData()
            setRunDirectory file('run/data')
            programArguments.addAll(
                    '--all', '--mod', "${project.mod_id}",
                    '--output', file('../src/generated/resources').absolutePath,
                    '--existing', file('../src/main/resources').absolutePath
            )
        }
    }

    neoForge {
        convertAccessWideners(tasks.named('shadowJar'), 'inkraft.accesswidener')
    }
}

tasks.named('check') {
    dependsOn tasks.named('runGameTestServer')
}

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"

    // A workaround in 26.1 for https://github.com/PaperMC/adventure-platform-mod/issues/255
    // See https://github.com/PaperMC/adventure-platform-mod/pull/263#issuecomment-4994500220
    implementation(include("net.kyori:adventure-platform-neoforge:${rootProject.adventure_platform_version}")) {
        exclude group: 'net.kyori', module: 'adventure-platform-mod-shared'
    }
    compileOnly("net.kyori:adventure-platform-neoforge:${rootProject.adventure_platform_version}")

    common(project(':')) { transitive false }
    shadowBundle project(path: ':', configuration: 'transformProductionNeoForge')
}
